version: '3.7'

services:
  rabbit-service:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-service
            
    ports:
      - "15672:15672"
      - "5671:5671"
    
    volumes:
      - "./rabbitmq/conf.d:/etc/rabbitmq/conf.d"
      - ~/storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/storage/rabbitmq/log/:/var/log/rabbitmq
      - ./storage/certs:/certs
